### ISSUE TITLE
Wider erwartetes Verhalten bei der Angabe von `start_callback_type` und `end_event_id`

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/process_engine_client#6]
Wenn ich die URI wie folgt verwende, würde ich einen blockierenden HTTP-Aufruf erwarten:

`/api/consumer/v1/process_models/sample_external_task/start?startCallbackType=3&start_event_id=do_start&end_event_id=the_end`

was mache ich falsch?!?

**Comment by moellenbeck** [comment]
@ElRaptorus hier ist ein Python-Sample https://github.com/5minds/process_engine_client-python/blob/feature/alternative_external_task_impl/samples/process_control.py#L15 //cc @rrrene

**Comment by ElRaptorus** [comment]
> @ElRaptorus hier ist ein Python-Sample https://github.com/5minds/process_engine_client-python/blob/feature/alternative_external_task_impl/samples/process_control.py#L15 //cc @rrrene

Der Link scheint ins Leere zu zeigen, oder auf ein Repo, auf das ich keinen Zugriff habe.

**Comment by ElRaptorus** [comment]
Hat sich geklärt.
